---
version: "3.8"
services:
  docker_exporter:
    image: cmosley/docker_exporter:latest
    command: --verbose
    ports:
     - 9417:9417
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped